# ABOUTME: Canonical change type constants for the IR diff algorithm.
# ABOUTME: Single source of truth for all ~50 change type string identifiers.

# --- Metadata and root ---
IR_METADATA_CHANGED = "IR_METADATA_CHANGED"
ROOT_CHANGED = "ROOT_CHANGED"

# --- Sheet-level ---
SHEET_ADDED = "SHEET_ADDED"
SHEET_REMOVED = "SHEET_REMOVED"
SHEET_RENAMED = "SHEET_RENAMED"

# --- Row/column axis edits ---
ROWS_INSERTED = "ROWS_INSERTED"
ROWS_DELETED = "ROWS_DELETED"
COLS_INSERTED = "COLS_INSERTED"
COLS_DELETED = "COLS_DELETED"

# --- Defined names ---
NAME_ADDED = "NAME_ADDED"
NAME_REMOVED = "NAME_REMOVED"
NAME_DESTINATIONS_CHANGED = "NAME_DESTINATIONS_CHANGED"
NAME_METADATA_CHANGED = "NAME_METADATA_CHANGED"

# --- Table candidates ---
TABLE_CANDIDATE_ADDED = "TABLE_CANDIDATE_ADDED"
TABLE_CANDIDATE_REMOVED = "TABLE_CANDIDATE_REMOVED"
TABLE_CANDIDATE_CHANGED = "TABLE_CANDIDATE_CHANGED"

# --- Binding-level ---
BINDING_ADDED = "BINDING_ADDED"
BINDING_REMOVED = "BINDING_REMOVED"
BINDING_NOW_IN_SCOPE = "BINDING_NOW_IN_SCOPE"
BINDING_OUT_OF_SCOPE = "BINDING_OUT_OF_SCOPE"
BINDING_MOVED = "BINDING_MOVED"
BINDING_RESIZED = "BINDING_RESIZED"
BINDING_TYPE_CHANGED = "BINDING_TYPE_CHANGED"
BINDING_FORMULA_CHANGED = "BINDING_FORMULA_CHANGED"
BINDING_LABEL_CHANGED = "BINDING_LABEL_CHANGED"
BINDING_METADATA_CHANGED = "BINDING_METADATA_CHANGED"

# --- Cell-level ---
FORMULA_CHANGED = "FORMULA_CHANGED"
VALUE_CHANGED = "VALUE_CHANGED"
FORMAT_CHANGED = "FORMAT_CHANGED"
EXTRAS_CHANGED = "EXTRAS_CHANGED"
DTYPE_CHANGED = "DTYPE_CHANGED"
ARRAY_FORMULA_FLAG_CHANGED = "ARRAY_FORMULA_FLAG_CHANGED"
SPILL_CHANGED = "SPILL_CHANGED"

# --- Dependency graph ---
CELL_EDGE_ADDED = "CELL_EDGE_ADDED"
CELL_EDGE_REMOVED = "CELL_EDGE_REMOVED"
RANGE_EDGE_ADDED = "RANGE_EDGE_ADDED"
RANGE_EDGE_REMOVED = "RANGE_EDGE_REMOVED"
RANGE_EDGE_COUNT_CHANGED = "RANGE_EDGE_COUNT_CHANGED"
EXTERNAL_EDGE_ADDED = "EXTERNAL_EDGE_ADDED"
EXTERNAL_EDGE_REMOVED = "EXTERNAL_EDGE_REMOVED"
BINDING_EDGE_ADDED = "BINDING_EDGE_ADDED"
BINDING_EDGE_REMOVED = "BINDING_EDGE_REMOVED"
BINDING_EDGE_WEIGHT_CHANGED = "BINDING_EDGE_WEIGHT_CHANGED"

# --- Label evidence ---
BINDING_LABEL_EVIDENCE_CHANGED = "BINDING_LABEL_EVIDENCE_CHANGED"

# --- Time annotations ---
TIME_INDEX_CANDIDATE_ADDED = "TIME_INDEX_CANDIDATE_ADDED"
TIME_INDEX_CANDIDATE_REMOVED = "TIME_INDEX_CANDIDATE_REMOVED"
TIME_INDEX_CANDIDATE_CHANGED = "TIME_INDEX_CANDIDATE_CHANGED"
BINDING_TIME_ANNOTATION_ADDED = "BINDING_TIME_ANNOTATION_ADDED"
BINDING_TIME_ANNOTATION_REMOVED = "BINDING_TIME_ANNOTATION_REMOVED"
BINDING_TIME_ANNOTATION_CHANGED = "BINDING_TIME_ANNOTATION_CHANGED"

# --- Resolution metrics ---
RESOLUTION_METRIC_ADDED = "RESOLUTION_METRIC_ADDED"
RESOLUTION_METRIC_REMOVED = "RESOLUTION_METRIC_REMOVED"
RESOLUTION_METRIC_CHANGED = "RESOLUTION_METRIC_CHANGED"

# --- Formula families (summary-only, not verification-active) ---
FAMILY_ADDED = "FAMILY_ADDED"
FAMILY_REMOVED = "FAMILY_REMOVED"
FAMILY_RESIZED = "FAMILY_RESIZED"
FAMILY_REPRESENTATIVE_CHANGED = "FAMILY_REPRESENTATIVE_CHANGED"
FAMILY_FORMULA_CHANGED = "FAMILY_FORMULA_CHANGED"

# --- Ordering tiers (lower number = earlier in output) ---
ORDERING_TIERS: dict[str, int] = {
    IR_METADATA_CHANGED: 0,
    ROOT_CHANGED: 1,
    # Sheets
    SHEET_ADDED: 2,
    SHEET_REMOVED: 2,
    SHEET_RENAMED: 2,
    # Rows/cols
    ROWS_INSERTED: 3,
    ROWS_DELETED: 3,
    COLS_INSERTED: 3,
    COLS_DELETED: 3,
    # Names
    NAME_ADDED: 4,
    NAME_REMOVED: 4,
    NAME_DESTINATIONS_CHANGED: 4,
    NAME_METADATA_CHANGED: 4,
    # Tables
    TABLE_CANDIDATE_ADDED: 5,
    TABLE_CANDIDATE_REMOVED: 5,
    TABLE_CANDIDATE_CHANGED: 5,
    # Bindings
    BINDING_ADDED: 6,
    BINDING_REMOVED: 6,
    BINDING_NOW_IN_SCOPE: 6,
    BINDING_OUT_OF_SCOPE: 6,
    BINDING_MOVED: 6,
    BINDING_RESIZED: 6,
    BINDING_TYPE_CHANGED: 6,
    BINDING_FORMULA_CHANGED: 6,
    BINDING_LABEL_CHANGED: 6,
    BINDING_METADATA_CHANGED: 6,
    # Cells
    FORMULA_CHANGED: 7,
    VALUE_CHANGED: 7,
    FORMAT_CHANGED: 7,
    EXTRAS_CHANGED: 7,
    DTYPE_CHANGED: 7,
    ARRAY_FORMULA_FLAG_CHANGED: 7,
    SPILL_CHANGED: 7,
    # Label evidence + time annotations
    BINDING_LABEL_EVIDENCE_CHANGED: 8,
    TIME_INDEX_CANDIDATE_ADDED: 8,
    TIME_INDEX_CANDIDATE_REMOVED: 8,
    TIME_INDEX_CANDIDATE_CHANGED: 8,
    BINDING_TIME_ANNOTATION_ADDED: 8,
    BINDING_TIME_ANNOTATION_REMOVED: 8,
    BINDING_TIME_ANNOTATION_CHANGED: 8,
    # Edges
    CELL_EDGE_ADDED: 9,
    CELL_EDGE_REMOVED: 9,
    RANGE_EDGE_ADDED: 9,
    RANGE_EDGE_REMOVED: 9,
    RANGE_EDGE_COUNT_CHANGED: 9,
    EXTERNAL_EDGE_ADDED: 9,
    EXTERNAL_EDGE_REMOVED: 9,
    BINDING_EDGE_ADDED: 9,
    BINDING_EDGE_REMOVED: 9,
    BINDING_EDGE_WEIGHT_CHANGED: 9,
    # Families (summary-only)
    FAMILY_ADDED: 10,
    FAMILY_REMOVED: 10,
    FAMILY_RESIZED: 10,
    FAMILY_REPRESENTATIVE_CHANGED: 10,
    FAMILY_FORMULA_CHANGED: 10,
    # Resolution metrics
    RESOLUTION_METRIC_ADDED: 11,
    RESOLUTION_METRIC_REMOVED: 11,
    RESOLUTION_METRIC_CHANGED: 11,
}

# Change types that are summary-only (not verification-active)
SUMMARY_ONLY_TYPES: frozenset[str] = frozenset(
    {
        FAMILY_ADDED,
        FAMILY_REMOVED,
        FAMILY_RESIZED,
        FAMILY_REPRESENTATIVE_CHANGED,
        FAMILY_FORMULA_CHANGED,
    }
)

# Change types produced by IR *inference* (the extractor's semantic layer:
# table-candidate detection, binding-label evidence gathering, time-axis
# annotation) rather than by a workbook edit. These can churn when IR
# segmentation shifts even though no cell changed, so consumers auditing
# workbook edits report them separately from the edit signal.
IR_INFERENCE_TYPES: frozenset[str] = frozenset(
    {
        TABLE_CANDIDATE_ADDED,
        TABLE_CANDIDATE_REMOVED,
        TABLE_CANDIDATE_CHANGED,
        BINDING_LABEL_EVIDENCE_CHANGED,
        TIME_INDEX_CANDIDATE_ADDED,
        TIME_INDEX_CANDIDATE_REMOVED,
        TIME_INDEX_CANDIDATE_CHANGED,
        BINDING_TIME_ANNOTATION_ADDED,
        BINDING_TIME_ANNOTATION_REMOVED,
        BINDING_TIME_ANNOTATION_CHANGED,
    }
)
